openapi: 3.0.3
info:
  title: Product Service API
  version: 1.0.0
  description: API for retrieving product list and product by ID.
servers:
  - url: https://f6012m8ype.execute-api.us-east-1.amazonaws.com/dev
paths:
  /products:
    get:
      summary: Get all products
      operationId: getProductsList
      responses:
        "200":
          description: A full array of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
  /products/{productId}:
    get:
      summary: Get a product by ID
      operationId: getProductsById
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Product found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    Product:
      type: object
      required:
        - id
        - title
        - description
        - price
        - count
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        image:
          type: string
        price:
          type: number
        count:
          type: integer
    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
